replit/polygott

languages/python3.toml

Doesn't seem like people use it on repl.it anyway, will `ls` for any usage on `gsutil`

Disable pycodestyle

---

languages/elisp.toml

Small mistake in the original `elisp.toml`.

Add .el extension for Elisp

---

languages/elisp.toml

It turns out that the Emacs from kelleyk is graphical, and it further turns out that the X support we have on Repl.it actually makes Emacs think that it can open a graphical window (even though it can't quite manage to). Revert for now, until we can figure out how to get a non-graphical build of Emacs 26.

Revert "Upgrade to Emacs 26"

---

languages/elisp.toml

See also: #24, #25.
We decided that the simplest solution to the X11 problem is to simply adjust Prybar to pass the `-nw` argument when starting Emacs, which is probably desirable anyway. It is not a terrible problem that Emacs tries to start an X11 frame if you launch it from the shell, because the Repl.it shell is not an officially supported feature. In future, we may fix the problem that prevents the frame from actually launching.

Upgrade to Emacs 26, attempt #2

---

.travis.yml
Makefile

Add a target to the Makefile that uses git to determine which languages have changed in the checked out ref vs. the `origin/master` remote. Travis now executes this test and also tests the whole polygott image in parallel.
Benefit: **contributors get much faster feedback if a branch or PR has failing language-specific tests**, instead of having to wait for the whole image to build. We still need the whole image tests to have confidence that there's no issue with dependencies, etc.
See https://travis-ci.org/replit/polygott/builds/551445267 for an example. Note that the build and test of the elisp image took under three minutes, whereas all of polygott was 35 min.

Test images with Travis

---

Makefile
README.md

We no longer use GCS, so the Makefile target and its accompanying documentation the README are no longer necessary.

Remove references to GCS

---

polygott-gitignore

This PR adds `.config/` and `.replit/` (UPM stores things in `.replit/upm`) to the standard set of git-ignored files in Polygott languages.

Ignore a couple more things in Polygott gitignore

---

gen/phase2.ejs

Otherwise `polygott-lang-setup -l elisp` will fail with permission denied because somebody thought it was cute to have package.el disable group and world permissions on `~/.emacs.d/elpa/gnupg`.
cc @kochman who reported this problem.
consulted with @turbio in person to confirm that transferring ownership is what we want to do.

Make runner own /opt/homes

---

gen/schema.json
languages/dart.toml

- Add LSP configuration for Dart
- Pin Dart to 2.2 (our LSP client doesn't work with newer versions; will solve this later)
- Use our apt machinery to install Dart instead of running ad-hoc commands
- Update schema to allow specific package versions

Configure Dart LSP

---

languages/dart.toml

We're a few versions behind since we were having LSP issues. I think it's preferable to stay up to date and just disable LSP for now.

Bump Dart to 2.5

---

languages/python3.toml

Polygott isn't actually used yet for Python 3 on Repl.it, but we should still track the most recent version.

Bump Python to 3.8

---

languages/webassembly.toml

This PRs follows the PR #39 , as the fix in Wasmer: https://github.com/wasmerio/wasmer/issues/818 reported by @jgautier is now published in the latest release 0.8.0.
Wasmer will compile and execute much faster the WebAssembly files (supporting also caching as well) so it will be a step-up for Repl.it 🙂

Update WebAssembly using Wasmer runtime

---

languages/dart.toml

- Bump Dart version to 2.5.2
- Symlink `pub` so the Dart UPM backend can find it

Symlink Dart pub and bump version

---

languages/ruby.toml

`/usr/local/bundle` doesn't exist and my understanding is that it doesn't need to. So the fix here is to stop chowning it.

Fix Ruby build

---

languages/c.toml
languages/cpp.toml

cquery should expect c++17. Backwards compatibility is really good
and it's annoying to see errors when writting c++17 code.

update version of c++ used by cquery

---

languages/scala.toml

`polygott` already installed Scala via `aptitude`. To make absolutely sure that this image and the `prybar` image use Scala 2.13.1, I explicitly pull down a versioned tarball. It's not clear whether we need to list `openjdk-11-jdk` as a dependency here, or if we should in `prybar`.

use scala 2.13.1

---

languages/java.toml

Let's fetch all the dependencies maven depends on at build time instead of when first running `upm add`.

run dependency:copy-dependencies during java build 

---

Dockerfile
build-prybar-lang.sh
fetch-prybar.sh
languages/julia.toml
packages.txt

Putting this up early to get 👀 ! We'd like polygott to explicitly depend on prybar (and, eventually, upm). During any polygott build, we'll fetch a tag of prybar. Individual languages can then build the `prybar-${LANG}` binary they need.

Fetch prybar, build prybar-LANG for individual languages

---

Dockerfile
build-prybar-lang.sh
fetch-prybar.sh
languages/clojure.toml
languages/elisp.toml
languages/julia.toml
languages/lua.toml
languages/nodejs.toml
languages/ocaml.toml
languages/python.toml
languages/python3.toml
languages/ruby.toml
languages/scala.toml
languages/sqlite.toml
languages/tcl.toml
packages.txt

Each language in polygott that has a prybar interpreter now builds that prybar binary.
Most prybar binaries do not pass the polygott tests, since they seem to not flush stdout:
```
root@6a340446f99e:/home/runner# cat main.lua 
print("hello")
root@6a340446f99e:/home/runner# lua main.lua | cat
hello
root@6a340446f99e:/home/runner# prybar-lua -q main.lua | cat
root@6a340446f99e:/home/runner# prybar-lua -q main.lua
hello
```
This means that most prybar interpreters (except julia, python3, and tcl) are not currently covered by polygott tests! The only way to end-to-end test these languages is to run them in a local goval.
Here's my TODO list as it stands after pushing up this branch:
```
julia
python3
tcl
R
spidermonkey
clojure
elisp
lua
nodejs
ocaml
python2
ruby
scala
sqlite
```

Install prybar binaries as part of building a language

---

Dockerfile
build-prybar-lang.sh
fetch-prybar.sh

Some prybar binaries expect to be able to read files from a `prybar_assets` directory that *must be a sibling* of the prybar binary. So we copy `prybar_assets` to `/usr/bin/` both when we fetch prybar AND when we build a language (some language's assets are created at build time).

Install `prybar_assets` next to prybar binaries

---

gen/index.js
gen/schema.json

@kochman laid the ground work for, say, `pygame` to depend on `python3`, which is helpful! Figured I'd land this separate from the language changes, since it's handy on its own.

cherry pick sid's work to let langs depend on other langs

---

languages/cpp.toml
languages/cpp11.toml

Added argument `-std=c++17` for cpp.
Remove `.cquery` file and replaced it with cquery argument `extraClangArguments`

Use std c++17 for cpp

---

languages/raku.toml

Renamed perl6.toml to raku.toml and added `raku`, `nqp`, and `moar` to `/usr/local/bin`.

Rename perl6.toml to raku.toml

---

languages/python3.toml

During the `python3_beta` rollout, people were seeing spurious `pycodestyle` errors. We configure `pyls` to ignore warnings and errors from `pycodestyle` (`pyflakes` is what counts, says @masad-frost). Why not go all the way and not install `pycodestyle` in the first place?
A good test case on repl.it is:
```
for x in range(5):
print(x)
```
You should see red squiggles under `print(x)` and a single warning from `pyflakes`.

do not install pycodestyle so pyls only uses pyflakes

---

languages/raku.toml

Existing repls that use `.p6` instead of `.raku` don't work now.

Raku should detect .p6 extensions too

---

languages/deno.toml

This installs the typescript-language-server for deno.
It's temporary, until deno releases their own LSP.

Added typescript-language-server for deno

---

packages.txt

"Opus support" has been requested many times and is needed for many applications handling audio, eg discord bots.

Add opus to polygott languages

---

gen/schema.json
languages/go.toml

We went from Go 1.13 to Go 1.14 without intentionally deciding to make the jump! We should pin this. I think it's okay if we let patch releases slide through (e.g. 1.14.1 to 1.14.2).
I added a test to make sure that `run-project` uses the expected version of Go.

pin Go version

---

gen/x11-vnc.ejs

Starting X11 on repl.it can seem noisy, and some people think something's gone wrong because they see a lot of output, some of it in red! Let's redirect the X11 output to a log file under `/tmp`.

redirect polygott-x11-vnc output to /tmp/polygott-x11-vnc.log

---

Dockerfile
gen/phase1.ejs
gen/phase2.ejs
languages/pygame.toml
languages/python3.toml
languages/pyxel.toml

In order to cache python3 packages in the repl workspace, we're going to 
* stop creating a virtualenv in polygott,
* and explicitly set $PYTHONUSERBASE downstream.
This change removes virtualenv creation from polygott. We should not merge it until downstream images have configured poetry to never create virtualenvs.

install python3 packages into default site packages location

---

README.md
languages/deno.toml

What I'm interested in: 
* This fixes issues with lockfile generation for long-lived programs (https://github.com/denoland/deno/pull/5794). Needed to introduce deno lockfiles on repl.it
* This introduces deno's super fast linter
(Also found a smol typo in readme)

Updated deno to 1.1

---

languages/python3.toml

This version was in #103 which got reverted in #107. But any lockfiles that were written while #103 was out are not compatible with the version of Poetry (0.12.16) before #103 and after #107.

bump Poetry to 1.0.5

---

.circleci/config.yml

I, for one, would like to be able to approve & merge PRs on here without worrying that we're breaking anything downstream. To do that, we need to be able to peg the polygott version downstream. Let's tag the image with the commit sha so we can do that!

tag and push polygott with git commit hash

---

packages.txt

Now that we "added" [selenium support](https://replit.canny.io/admin/feedback/bug-reports/p/python-3-selenium?boards=bug-reports&sort=top&status=open), it'd be cool if we can also support launching Firefox as well as Chrome so that people can use `webdriver.Firefox()` and `webdriver.Chrome()`.
This would increase browser coverage for people who are actually using Selenium for its intended purpose but also give users some more choice. Obviously, adding Safari, Edge, etc would be ideal too but alas we're running on Linux.

Add firefox-geckodriver to installed packages

---

Dockerfile

https://github.com/replit/prybar/pull/53 made prybar-python3 set the environment variable $VIRTUAL_ENV as the prefix, meaning that prybar-python3 will pick up site packages from an activated virtualenv.
I've tested this branch locally; it should behave identically to the current prybar-python3 that ships with polygott.

use prybar-python3 that honors $VIRTUAL_ENV

---

Dockerfile

Had to back out the prybar change #118 was picking up: https://github.com/replit/prybar/pull/54
Reverts replit/polygott#118

Revert "use prybar-python3 that honors $VIRTUAL_ENV"

---

languages/python3.toml

Running tensorflow on repl.it is tough at the moment: you have to install the correct version by hand. Let's pre-install `tensorflow-cpu`, which we know works.

pre-install tensorflow on python3

---

languages/nextjs.toml

In the nextjs file the mkdir command makes a directory in the wrong directory. The pull request fixes that.

Changed it to /home/runner instead.

---

languages/prolog.toml

It's been requested quite a bit, so I figured that I'd add it.

Add GNU Prolog support

---

languages/ruby.toml

Adds the `libsqlite3-dev` package to the ruby image. This package is required by Ruby on Rails.

Add libsqlite3-dev package to Ruby

---

languages/kotlin.toml

Kotlin hasn't been updated since we first introduced support. Updating has the following benefits:
- no longer have to pass args String array param to `main` (see https://play.kotlinlang.org/byExample/01_introduction/01_Hello%20world)
- Gets rid of reflective access operation [warning](https://user-images.githubusercontent.com/24947334/88346813-1556f000-ccfe-11ea-8243-b4469a76069e.png) that started appearing when we updated Kotlin to point to the polygott image.
- Whatever features/fixes have been added since 1.0.3

Update Kotlin to v1.3.72

---

Dockerfile
gen/index.js
gen/schema.json
languages/objective-c.toml
languages/ocaml.toml

So I added Objective-C as a supported language, along with the GNUstep libraries that are commonly associated with it. I also changed some stuff to let the `setup` section have strings that span multiple lines (why didn't that exist before?). Finally, I made it so that only command-line arguments that contains spaces are quoted, as quoting every non-identifier was pretty annoying and required passing everything to a bash command in order to avoid that. (None of those changes break other language configs btw)

Add Objective-C (with GNUstep!)

---

languages/python3.toml

Don't use a pinned version for `replit` so that new version will install.

Make python3 use latest replit package version

---

languages/powershell.toml

bump powershell version to v7.0.3
added a symlink to /usr/bin/powershell so both pwsh and powershell commands work

bump version and link command powershell

---

languages/forth.toml

The version of gforth that ubuntu has is really old, so this uses more up-to-date versions of gforth 0.7.9

Update gforth to 0.7.9

---

.circleci/config.yml
Dockerfile
languages/go.toml

This fixes 3 different issues with CI:
* ~~Ballerina lang's dist website has an expired cert. I've reached out on their Slack, hopefully this will get fixed so we don't have to change anything here. (Once fixed, I'll remove the commit that disables cert checking for Ballerina)~~ (cert was fixed)
* Go 1.15 uses a syscall that CircleCI doesn't support, this has been fixed on Go's side and will be released in the next minor release. Until then, pinning the Docker version on CI seems to fix the issue.
* The `go.toml` Go version pinning was not working properly. I got around this by downloading go directly from golang's site, and installing it at `/usr/local/go/` and then updating the `$PATH` to include the downloaded version of Go. This allows the image building to use a different version of …

Fix CI Errors

---

gen/phase1.ejs
gen/x11-vnc.ejs

Ubuntu pushed a couple of security patches to the apt version of `libvncserver` that broke compatibility with novnc. This PR builds and installs `libvncserver` from source to fix the issue.

X11 support has been broken since at least June 24

---

languages/pygame.toml

This was causing CI to fail in https://github.com/replit/polygott/pull/190
Let's get rid of this test since it will always fail anytime Pygame is upgraded upstream

Remove pygame import test

---

languages/elixir.toml

We've been stuck on Elixir v1.3.3 and Erlang/OTP 20.0 for a while now and a lot of people have been asking us to upgrade since we're missing quite a few features (e.g. [defguards](https://hexdocs.pm/elixir/patterns-and-guards.html#custom-patterns-and-guards-expressions)).
Looks like 1.3.3 is the latest version you can install on Ubuntu bionic (https://packages.ubuntu.com/bionic/elixir) so we'll have to fetch the latest precompiled package first and install manually.

Upgrade Elixir to 1.11.2, Erlang/OTP 23.0

---

gen/x11-vnc.ejs

Reverts replit/polygott#180
I'm seeing many errors that look like this when running `pygame` repls:
```
 bash -c polygott-x11-vnc q && DISPLAY=:0 run-project
......pygame 2.0.0 (SDL 2.0.12, python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Warning, no sound
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  42 (X_SetInputFocus)
Serial number of failed request:  195
Current serial number in output stream:  196
exit status 1
```
With this revert, we'll tradeoff some hangs for being able to start X11 at all.

Revert "kill X before possibly starting another X"

---

.circleci/config.yml
Makefile

This change creates the `replco/polygott-ci` image, which contains the
subset of languages needed for CI, in an attempt to get a smaller image
going.

Build an image with just the languages needed for CI

---

languages/python3.toml

LSP in Python is currently not working very well (e.g. everything listed in this blog has regressed: https://blog.repl.it/intel). In particular, go to definition, find references, etc is broken across files and modules (including built in modules like `os`, `time`, etc).
This seems to be due to the fact that we've upgrade Python versions (from ~3.5 -> 3.8) but haven't touched `python-language-server` and its dependencies (`jedi`, `pyflakes`, etc) since which are now almost all over 2 years old.
Upgrading them seems to do the trick (I tested this locally and made sure all of the examples in the above blog work again)

Upgrade python-language-server and related packages

---

gen/index.js
gen/phase1.ejs
gen/phase2.ejs
languages/cpp.toml
languages/cpp11.toml
languages/express.toml
languages/jest.toml
languages/nodejs.toml
languages/react_native.toml

This change now does a better job of tracking common dependencies and
common setup logic by better using the parent linkage between languages.
Now the `undup()` function is gone!

Avoid the setup-deduplicating logic by tracking child languages

---

Dockerfile
extra/fluxbox/apps
extra/fluxbox/init

https://replit.slack.com/archives/C85MLAXU2/p1611423618079800
This uses a trick on `fluxbox-apps(5)` to force any app to always start
at the top-left corner, overlapping if needed.

Make new fluxbox windows always start at (0,0)

---

gen/detect-language.ejs

I accidentally introduced a bug in a previous commit do to an
overzealous copy-paste, where the `detect-language` script would not try
to detect a language if a language was not explicitly passed in.

Fix the detect-language script

---

languages/ruby.toml
out/phase2.sh

This change allows previously-exisiting Gemfile.lock files to still be
loadable, as well as giving the masses access to the latest and
greatest.

[ruby] Install bundler 2.2.3 and 2.2.7

---

.dockerignore
.gitignore

It turns out that the semantics of the `.dockerignore` file does not quite
match the ones from `.gitignore` ^^;; For the former, we need to
explicitly mark a directory and all of its children as being ignored if
we want to have that rule be recursive.

Do a better job at ignoring stuff

---

gen/Dockerfile.ejs
languages/ruby.toml
out/Dockerfile
out/phase2.sh

This change enables the use of the fancy new Docker syntax, which allows
running a single `RUN` command with a mount from a previous phase or a
tmpfs. This is useful to avoid having to clean stuff out (like
/var/log).

Use the fancy new Docker builder syntax

---

extra/fetch-prybar.sh
gen/Dockerfile.ejs
out/Dockerfile

There is no need to involve alpine, since we already have a perfectly
reasonable base image already. This also gets rid of the fetch-prybar.sh
script for simplicity.

Use `polygott-phase0` as base image for the prybar resources

---

gen/Dockerfile.ejs
out/Dockerfile

This change will avoid creating these directories at container runtime.
It saves a few microseconds and makes everything tidier.

Explicitly create all mountpoints

---

.circleci/config.yml
.dockerignore
.gitignore
Makefile
extra/manifest_tool.py

This change further simplifies how the .gitignore and .dockerignore
files are used by having a single directory with ephemeral build
artifacts. In doing so, it also further locks down what files are even
considered in the Docker build context.

Move all the build-time artifacts to a build/ directory

---

out/phase0.sh
packages.txt

This is needed for getting /usr/bin/xwininfo, which is required for X11
activation.
Note: this will invalidate the cache and take forever again T_T.

Add x11-utils as a dependency

---

gen/Dockerfile.ejs
out/Dockerfile

This change adds rfbproxy. No buildtime shenanigans for this, courtesy
of GitHub CI n_n.

Add rfbproxy to polygott-tools

---

languages/raku.toml
out/phase0.sh
out/share/polygott/phase2.d/raku

This change fixes raku, which has changed the location of the
repository.
The URL was obtained by following the instructions in https://cloudsmith.io/~nxadm-pkgs/repos/rakudo-pkg/setup/#formats-deb, which ended up leding to 
```shell
$ curl 'https://dl.cloudsmith.io/public/nxadm-pkgs/rakudo-pkg/config.deb.txt?distro=Ubuntu&codename=bionic&version=18.04&arch=amd64'
deb https://dl.cloudsmith.io/public/nxadm-pkgs/rakudo-pkg/deb/ubuntu bionic main
deb-src https://dl.cloudsmith.io/public/nxadm-pkgs/rakudo-pkg/deb/ubuntu bionic main
```

Fix the raku build

---

languages/deno.toml
out/share/polygott/phase2.d/deno

This upgrades deno to 1.8!
Changelog here: https://deno.land/posts/v1.8. I'm excited about `deno lsp` being stable.

🦕 Update deno to 1.8.1 

---

extra/manifest_tool.py

Fixes #231. Changes shebang in `extra/manifest_tool.py` to force `python3` as suggested by @lhchavez.

Fix python version

---

README.md

This change adds a paragraph in the README.md explaining how to
re-generate the build artifacts.

Document the need for the files in out/ to be committed

---

languages/crystal.toml
out/Dockerfile
out/phase0.sh

Crystal has recently updated to its first major release (`1.0.0`) following some updates to their `apt` and `rpm` repositories. Some installation methods have been updated for Crystal, and this PR reflects those changes in `crystal.toml`.
+ [`Crystal 1.0`](https://crystal-lang.org/2021/03/22/crystal-1.0-what-to-expect.html)
+ [`Install on Ubuntu`](https://crystal-lang.org/install/on_ubuntu/)
+ [`Announcing new apt and rpm repositories`](https://crystal-lang.org/2020/08/24/announcing-new-apt-and-rpm-repositories.html)
These changes have yet to be tested (too much schoolwork 😰), but they shouldn't break anything *hopefully*.

Update Crystal (1.0.0)

---

README.md

The links in your README all link to your old domain `https://repl.it/`. Just to get it over with, I switched them out to `https://replit.com/` :).

Update README with Replit.com

---

languages/python3.toml
out/share/polygott/phase2.d/python3

We noticed a lot of slowness with python autocomplete. It seems like there's a regression with Jedi version 0.16.0+ in combination with pyls.
Downgraded `jedi` to version `0.15.2`, the latest `pyls` version that supports it is `0.31.10`. 
`pyls` `0.31.10` has an issue where it depends on `ujson<=1.35`, it also depends on `python-jsonrpc-server>=0.3.2`, however new versions of `python-jsonrpc-server` rely on `ujson>=3.0.0`, leading to problems with pip installation and the packages themselves. So I had to pin `python-jsonrpc-server` to `0.3.2`.
Things seemed to work, however, I started facing issues with some lsp features. Turns out jedi relies on `parso==0.5.2` but it doesn't pin it. So I decided to pin everything that pyls & its packages rely on. When I got to a working configuration …

Fix python language server being slow

---

languages/deno.toml
out/share/polygott/phase2.d/deno

Deno **v1.9.0** dropped! Among the new features are:
- Native HTTP/2 Server
- Huge performance improvements
- Support for blob and data URLs
- LSP improvements
- More configurable permissions
The full changelog is located [here](https://deno.com/blog/v1.9)

🦕 Update deno to v1.9.0

---

gen/index.js
out/Dockerfile.splice

Turns out that _some_ libraries install their `.pc` files in share.

Add /home/runner/.apt/usr/share/pkgconfig to the `PKG_CONFIG_PATH`

---

languages/raku.toml
out/Dockerfile
out/share/polygott/phase2.d/raku

This change stops Raku from installing updates beyond 2021.3.0-01, since
that breaks our already brittle CI.

Pin Raku to version 2021.3.0-01

---

languages/c.toml
languages/python3.toml
out/share/polygott/phase2.d/c
out/share/polygott/phase2.d/python3

This change makes it possible to add a debugger for native code and Python, using
Microsoft's Debug Adapter Protocol.

Install the Debug Adapter Protocol tools for C/C++/Python

---

.dockerignore
extra/nixproxy.nix
gen/Dockerfile.ejs
out/Dockerfile

give us a bit of future leeway on how we structure the nix experience. This expects a `replit.nix` in the repldir giving us the set `deps` which are passed right into nix-shell.
for example, something like:
```
{ pkgs }: {
deps = [
pkgs.python39
];
}
```

add nixproxy.nix to grab pkgs from repl's replit.nix

---

languages/c.toml
out/share/polygott/phase2.d/c

For some reason, `set -ev` has failed me.
This change should correctly extract the DAP tools in the right place.

Fix the extraction of the C++ DAP tools

---

languages/crystal.toml
out/phase0.sh

bintray is no longer. Let's use the new hotness that is OBS.
This should fix the master build.
Fixes: #247

Download Crystal from OBS instead of bintray

---

.circleci/config.yml
gen/index.js

This change makes it such that when run in Windows, no `\r` characters
are inserted, causing the CI test to fail.

Avoid Windows newline issues

---

Makefile

We may need to start testing some Nix-specific things in goval CI, so lets make sure Nix is included in the polygott CI image.
@lhchavez do I need to update anything on the goval side after merging this or will it always pick up the latest polygott-ci image?

Add nix to the CI image

---

languages/deno.toml
out/share/polygott/phase2.d/deno

This is an update for Deno to version 1.10.2. **This update addresses CVE-2021-32619, which is a vulnerability since v1.5.0.**
There are other changes in this release since 1.9.0 that can be found [here](https://deno.com/blog/v1.10).

[Security Patch]🦕 Update Deno to v1.10.2

---

.dockerignore
extra/java-dap
extra/py-dap
gen/Dockerfile.ejs
out/Dockerfile

This change makes the Python and Java DAPs be able to use ephemeral
ports instead of a hardcoded one. This should prevent an old process
that had opened the port (that did not enable port reuse) from blocking
new processes to open it.

Let the Python and Java DAPs choose the TCP port

---

gen/Dockerfile.ejs
gen/phase0.ejs
languages/swift.toml
out/Dockerfile
out/phase0.sh
out/share/polygott/phase2.d/swift

We were previously abusing `XDG_CONFIG_HOME` and setting it to a global
directory: `/config`.
This change starts a slow transition by setting the more correct
`XDG_CONFIG_DIRS=/config` and adding a few `source`-include commands in
the bash dotfiles in `~` to also support that.

Pave the road towards XDG-compliance (read: dotfiles in repls!)

---

Makefile
languages/nix.toml
languages/python3.toml
out/share/polygott/phase2.d/python3
out/share/polygott/self-test.d/nix
out/test.sh

This change allows us to use a new experiment to create a virtualenv
that doesn't need to copy all the files. That way we can create
virtualenvs inside the repl without it ballooning in size.
This change updates pip from v19.3.1 to v21.2.dev0 and drops dephell
altogether.

python3: Use replit's version of pip instead of the official one
