languages/sqlite.toml
=> Add SQLite

languages/elisp.toml
As suggested in https://www.reddit.com/r/emacs/comments/c5df1x/adding_a_language_to_replit_emacs_lisp/es19ksb.
=> Upgrade to Emacs 26

languages/webassembly.toml
Adding support for web assembly using wasmtime https://github.com/CraneStation/wasmtime
=> add wasm support using wasmtime

languages/webassembly.toml
Update wasmer version to 0.10.1
=> Update wasmer version to 0.10.1

packages.txt
=> add valgrind and glibc debug symbols

languages/pygame.toml, languages/python3.toml, languages/pyxel.toml
=> sid's python3 changes

Dockerfile, gen/phase1.ejs, gen/phase2.ejs, languages/pygame.toml, languages/python.toml, languages/python3.toml, languages/pyxel.toml
Also install all python3 dependencies into a virtualenv.
=> Make sure `pyls` works for Python 3

languages/deno.toml
Why
===
We decided to add deno: [internal slack link]
What changed
============
Added deno as a language on polygott.
Test plan
=========
1. Installed deno on polygott: (this)
2. Installed deno on eval server
3. Installed deno on frontend
4. Ran deno code. It runs!
=> Added deno 🦕

languages/python3.toml
Added the `replit` pip dependency to python3.
=> Added the replit dependancy to python

packages.txt
Added opusfile to the polygott dependencies to allow decoding and encoding .opus files in polygott languages.
=> Add opusfile

languages/python3.toml
Updated the pip replit package.
=> Updated replit

languages/assembly.toml
This pull request adds support for 64-bit assembly language using NASM. I tested it, and it builds and runs fine.
=> add assembly

languages/nim.toml
We had been using Nim 0.17.2 which is like 2 years old, so I thought it'd be nice to update it. Nim tools such as Nimble (package manager) have also been updated.
=> Update Nim to version 1.2

languages/rust.toml
Updated Rust from 1.36.0 to 1.44.0
=> Update Rust to 1.44.0

Dockerfile, gen/phase1.ejs, gen/phase2.ejs, languages/pygame.toml, languages/python3.toml, languages/pyxel.toml
=> Revert "install python3 packages into default site packages location"

languages/python3.toml
Updated the replit package for python3 to v1.2.2
=> Updated the replit package to 1.2.2

languages/python3.toml
Accidentally left an error w/ pausing in v1.2.2 so I have to fix that.
=> Updated replit to 1.2.3

Dockerfile
For some reason rust's cargo requires it https://twitter.com/oliverjumpertz/status/1279159118381617152
=> Add USER environment variable

README.md
It's not very clear how to contribute to polygott, this isn't much but at least its a start.
=> Added a link to our blog on adding elisp to the readme

languages/cpp.toml, languages/cpp11.toml
`.cc` is a popular extension in C++ projects
=> Add .cc to C++ extensions list

languages/pascal.toml
Should be self-explanatory; just a minor fix.
=> Remove extra main.pas argument

gen/inside-test.ejs, gen/lang-setup.ejs, languages/haxe.toml
Simple enough I think. I also installed HashLink since that's a commonly used backend for Haxe. Tried adding language server support, but I just went with whatever the compiler comes with since I couldn't figure out how to install [the normal language server](https://github.com/vshaxe/haxe-language-server). I also had to change some stuff to get the tests to run `polygott-lang-setup` since that's kinda important.
=> Add Haxe support

Makefile
We missed adding this one language to the bundle :facepalm:.
=> Add java10 to the polygott-ci image

.circleci/config.yml, .dockerignore, .gitignore, Dockerfile, Makefile, gen/phase0.ejs, gen/phase1.ejs, gen/phase2.ejs
This change removes most of the stuff that happened between the language
phases and moves that either before or after. This should facilitate the
next hefty goal: compiling one Dockerfile per language and then have a
post-processing step that merges 'em all together.
=> Reorder the polygott phases

Dockerfile, Makefile, gen/detect-language.ejs, gen/index.js, gen/phase1.ejs, gen/phase2.ejs, gen/run-language-server.ejs, gen/self-test-per-lang.ejs, gen/self-test.ejs, gen/tests.ejs, languages/forth.toml, languages/nim.toml
This should make it easier to reason about the tests and stuff.
This is also a good intermediate stopping point before I start making deep surgery into the Dockerfile.
=> Split some of the generated files

Dockerfile, gen/phase0.ejs, gen/phase2.ejs, languages/c.toml, languages/clojure.toml, languages/elixir.toml, languages/enzyme.toml, languages/erlang.toml, languages/fsharp.toml, languages/gatsbyjs.toml, languages/nextjs.toml, languages/nodejs.toml, languages/pygame.toml, languages/python.toml, languages/python3.toml, languages/pyxel.toml, languages/quil.toml, languages/reactjs.toml, languages/reactts.toml, packages.txt
This is a symptom of languages installing apt packages without going
through the proper channels. Ballerina and python are still installing
a `.deb` on their own, but that shouldn't touch the apt lists (right??).
=> Complain if a language setup tries to touch apt lists

languages/ballerina.toml, languages/flow.toml, languages/scala.toml, out/detect-language, out/phase1.sh, out/phase2.sh, out/polygott-lang-setup, out/polygott-survey, out/run-language-server, out/run-project, out/self-test, out/test.sh
This change:
* Makes scala depend on Java (so that it doesn't need to explicitly
install the OpenJDK package).
* Makes flow depend on nodejs (since it's calling npm).
* Updates Ballerina to the latest and greatest so that it doesn't depend
on OpenJDK 8. It now works with OpenJDK 11, so there's no use to
install two versions of Java.
=> Small language tweaks

.circleci/config.yml, Makefile, README.md, gen/Dockerfile.ejs, gen/index.js, languages/ballerina.toml, languages/flow.toml, languages/scala.toml, out/Dockerfile, out/detect-language, out/phase1.sh, out/phase2.sh, out/polygott-lang-setup, out/polygott-survey, out/run-language-server, out/run-project, out/self-test, out/test.sh
This change makes the Dockerfile be generated instead of hardcoded. This
allows further customization and can make it so that we avoid some of
the intermediate shell files.
=> Make the Dockerfile be a generated file

Makefile
This change lets us better track of what's been built so far with
explicit files. This allows us to perform fewer Docker invocations and
in general makes the build feel faster!
=> Track the build steps through stampfiles

languages/julia.toml, out/phase2.sh
Waited so long on https://github.com/replit/polygott/pull/185 that the PRYBAR_TAG location changed.
=> pull julia 1.4.1

.circleci/config.yml, extra/manifest_tool.py
This change introduces a tool for interacting with Docker image layers.
This will be used later to split/splice individual language images.
=> Introduce manifest_tool.py

Makefile
This change improves the stability of the Docker build context by
explicitly constructing it ourselves instead of letting Docker handle
that. Notably, this makes our files be immune to changes in the user's
umask (which makes the files have different permission bits, which
always invalidates the build cache) and mtime (which according to some
StackOverflow lore _may_ invalidate the build cache in some cases, but
I'm not quite positive about this).
=> Use the manifest_tool to create the Docker build context

out/phase0.sh, packages.txt
For sound and stuff, when we're ready.
=> Add pulseaudio

languages/nodejs.toml, out/phase0.sh
=> Upgrade Nodejs to 14.x

gen/Dockerfile.ejs, out/Dockerfile
This one supports the replit authentication, for moar security.
=> Use the newest version of rfbproxy

.dockerignore, extra/pulse/client.conf, extra/pulse/default.pa, gen/Dockerfile.ejs, out/Dockerfile
This change adds a few PulseAudio configuration overrides so that
PulseAudio can start reliably in Polygott.
Also, bump the rfbproxy at the same time since updating this is such a
pain D:
=> Add PulseAudio configuration files

extra/nixproxy.nix
made a lil oopsie woopsie. u_u
=> fix nixproxy file

languages/nix.toml, out/share/polygott/self-test.d/nix, out/test.sh
Actually test nix works roughly how we expect it to
=> add useful test for nix

languages/ruby.toml, out/phase0.sh, out/share/polygott/phase2.d/ruby, packages.txt
We're missing some locales :cry:
=> Add language-pack-en

gen/Dockerfile.ejs, out/Dockerfile
A new version of UPM is available, this PR updates polyglott to use the newer version.
=> Update the UPM hash

languages/deno.toml, out/share/polygott/phase2.d/deno
Back again with another update to Deno! This update includes Abortable fetch and WebCrypto APIs 
🦕🦕🦕🦕🦕
=> 🦕 Update Deno to v1.11.0
